name: NuGet Publish

on:
  push:
    branches: ["main"]
    tags: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            10.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore src/WUPHF.Shared/WUPHF.Shared.csproj

      - name: Build and pack
        run: dotnet pack src/WUPHF.Shared/WUPHF.Shared.csproj -c Release -o artifacts/packages

      - name: Authenticate with GitHub NuGet registry
        run: dotnet nuget add source --username dotnet-felickz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dotnet-felickz/index.json"

      - name: Publish to GitHub NuGet registry
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: dotnet nuget push artifacts/packages/*.nupkg --source github --skip-duplicate

      - name: Generate artifact attestation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-path: 'artifacts/packages/*.nupkg'

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: packages
          path: artifacts/packages
